export const THEM_MODAL = "THEM_MODAL";
export const SUA_MODAL = "SUA_MODAL";

export const THEM_CONG_VIEC_MODAL = "THEM_CONG_VIEC_MODAL";
export const SUA_CONG_VIEC_MODAL = "SUA_CONG_VIEC_MODAL";

export const THEM_LOAI_CONG_VIEC_MODAL = "THEM_LOAI_CONG_VIEC_MODAL";
export const SUA_LOAI_CONG_VIEC_MODAL = "SUA_LOAI_CONG_VIEC_MODAL";

export const THEM_DICH_VU_MODAL = "THEM_DICH_VU_MODAL";
export const SUA_DICH_VU_MODAL = "SUA_DICH_VU_MODAL";
